# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.worker_schedule.v1 import worker_schedule_pb2 as rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc/worker_schedule/v1/worker_schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerScheduleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/worker_schedule.v1.WorkerScheduleService/RegisterWorker',
                request_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.ListWorkers = channel.unary_unary(
                '/worker_schedule.v1.WorkerScheduleService/ListWorkers',
                request_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListWorkersRequest.SerializeToString,
                response_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListWorkersResponse.FromString,
                _registered_method=True)
        self.UpdateWorkerStatus = channel.unary_unary(
                '/worker_schedule.v1.WorkerScheduleService/UpdateWorkerStatus',
                request_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.UpdateWorkerStatusRequest.SerializeToString,
                response_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.UpdateWorkerStatusResponse.FromString,
                _registered_method=True)
        self.SyncOrderEvent = channel.unary_unary(
                '/worker_schedule.v1.WorkerScheduleService/SyncOrderEvent',
                request_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.SyncOrderEventRequest.SerializeToString,
                response_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.SyncOrderEventResponse.FromString,
                _registered_method=True)
        self.ListDailySchedule = channel.unary_unary(
                '/worker_schedule.v1.WorkerScheduleService/ListDailySchedule',
                request_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListDailyScheduleRequest.SerializeToString,
                response_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListDailyScheduleResponse.FromString,
                _registered_method=True)
        self.GetOrderDetail = channel.unary_unary(
                '/worker_schedule.v1.WorkerScheduleService/GetOrderDetail',
                request_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.GetOrderDetailRequest.SerializeToString,
                response_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.GetOrderDetailResponse.FromString,
                _registered_method=True)


class WorkerScheduleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncOrderEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDailySchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerScheduleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'ListWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkers,
                    request_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListWorkersRequest.FromString,
                    response_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListWorkersResponse.SerializeToString,
            ),
            'UpdateWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkerStatus,
                    request_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.UpdateWorkerStatusRequest.FromString,
                    response_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.UpdateWorkerStatusResponse.SerializeToString,
            ),
            'SyncOrderEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncOrderEvent,
                    request_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.SyncOrderEventRequest.FromString,
                    response_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.SyncOrderEventResponse.SerializeToString,
            ),
            'ListDailySchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDailySchedule,
                    request_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListDailyScheduleRequest.FromString,
                    response_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListDailyScheduleResponse.SerializeToString,
            ),
            'GetOrderDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderDetail,
                    request_deserializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.GetOrderDetailRequest.FromString,
                    response_serializer=rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.GetOrderDetailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker_schedule.v1.WorkerScheduleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker_schedule.v1.WorkerScheduleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerScheduleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_schedule.v1.WorkerScheduleService/RegisterWorker',
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.RegisterWorkerRequest.SerializeToString,
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_schedule.v1.WorkerScheduleService/ListWorkers',
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListWorkersRequest.SerializeToString,
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_schedule.v1.WorkerScheduleService/UpdateWorkerStatus',
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.UpdateWorkerStatusRequest.SerializeToString,
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.UpdateWorkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncOrderEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_schedule.v1.WorkerScheduleService/SyncOrderEvent',
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.SyncOrderEventRequest.SerializeToString,
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.SyncOrderEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDailySchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_schedule.v1.WorkerScheduleService/ListDailySchedule',
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListDailyScheduleRequest.SerializeToString,
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.ListDailyScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_schedule.v1.WorkerScheduleService/GetOrderDetail',
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.GetOrderDetailRequest.SerializeToString,
            rpc_dot_worker__schedule_dot_v1_dot_worker__schedule__pb2.GetOrderDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
